name             'buildpack'
maintainer       'Yamashita, Yuu'
maintainer_email 'yuu@treasure-data.com'
source_url       'https://github.com/yyuu/chef-buildpack'
license          'Apache 2.0'
description      'Installs/Configures application with using buildpack'
long_description 'Installs/Configures application with using buildpack'
version          '0.6.0'
