name             'buildpack'
maintainer       'Yamashita, Yuu'
maintainer_email 'yuu@treasure-data.com'
license          'Apache 2.0'
description      'Installs/Configures application with using buildpack'
long_description 'Installs/Configures application with using buildpack'
version          '0.5.1'
